server:
  port: ${SERVER_PORT:8075}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
  shutdown: graceful
  jetty:
    threads:
      max: 200
      min: 10
      idle-timeout: 60000
    connection-idle-timeout: 30000

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      server:
        webflux:
          routes:
            - id: resource-service
              uri: ${RESOURCE_SERVICE_URI:lb://resource-service}
              #              uri: http://localhost:8071
              predicates:
                - Path=/resources/**
                - Method=GET,POST,DELETE

            - id: song-service
              uri: ${SONG_SERVICE_URI:lb://song-service}
              #              uri: http://localhost:8072
              predicates:
                - Path=/songs/**
                - Method=GET,POST,DELETE

  application:
    name: api-gateway-service

  lifecycle:
    timeout-per-shutdown-phase: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    async-client-initialization: true

logging:
  pattern:
    console: '%highlight(%-5p) | %magenta(%d{ISO8601}{GMT}) | %cyan(%c) | %yellow(%m%ex%n)'
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        web.servlet.mvc.method.annotation: DEBUG
        cloud:
          loadbalancer: DEBUG
          client:
            loadbalancer: DEBUG
            core: DEBUG
            cache: DEBUG
            blocking: DEBUG
            reactive: DEBUG
            retry: DEBUG
  com:
    epam: TRACE
    zaxxer.hikari: DEBUG
    netflix:
      eureka: DEBUG
      discovery: DEBUG
