server:
  port: ${SERVER_PORT:8072}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${POSTGRE_URL:jdbc:postgresql://localhost:5432/song-db}
    username: ${POSTGRE_USER:postgres}
    password: ${POSTGRE_PASSWORD:password12@}
    driver-class-name: org.postgresql.Driver
    hikari.auto-commit: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  pattern:
    console: '%highlight(%-5p) | %magenta(%d{ISO8601}{GMT}) | %cyan(%c) | %yellow(%m%ex%n)'
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    hibernate:
      SQL: DEBUG
      orm:
        transaction: DEBUG
        jdbc:
          bind: TRACE
          extract: TRACE
      type:
        descriptor:
          sql: TRACE
    postgresql: DEBUG
  com:
    epam: TRACE
    zaxxer.hikari: DEBUG