server:
  port: ${SERVER_PORT:8071}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
    shutdown: graceful

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    discovery:
      enabled: true
      locator:
        enabled: true
    loadbalancer:
      client:
        enabled: true

  datasource:
    url: ${POSTGRE_URL:jdbc:postgresql://localhost:5432/resource-db}
    username: ${POSTGRE_USER:postgres}
    password: ${POSTGRE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: ResourceHikariPool
      max-lifetime: 1800000
  #      leak-detection-threshold: 10000

  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
    properties:
      ddl-auto: update
      format_sql: true
      jdbc:
        batch_size: 20
        order_inserts: true
        order_updates: true
      query:
        in_clause_parameter_padding: true
  hibernate:
    connection.provider_disables_autocommit: true

  application:
    name: resource-service

logging:
  pattern:
    console: '%highlight(%-5p) | %magenta(%d{ISO8601}{GMT}) | %cyan(%c) | %yellow(%m%ex%n)'
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        web.servlet.mvc.method.annotation: DEBUG
        transaction: DEBUG
        orm.jpa: DEBUG
        retry: DEBUG
        cloud:
          loadbalancer: DEBUG
          client:
            loadbalancer: DEBUG
            core: DEBUG
            cache: DEBUG
            blocking: DEBUG
            reactive: DEBUG
            retry: DEBUG
    hibernate:
      SQL: DEBUG
      type: TRACE
      orm:
        transaction: DEBUG
        jdbc:
          bind: TRACE
          extract: TRACE
    postgresql: DEBUG
  com:
    epam: TRACE
    zaxxer.hikari: DEBUG
    netflix:
      eureka: DEBUG
      discovery: DEBUG

  feign: DEBUG
  feign.Request: DEBUG
  feign.Response: DEBUG
  feign.Logger: DEBUG
  feign.retryer: DEBUG

  org.springframework.retry: DEBUG
  org.springframework.retry.policy: DEBUG

  org.apache.tika: DEBUG
  org.apache.tika.config: DEBUG
  org.apache.tika.parser: DEBUG

song:
  service:
    name: song-service
    base-url: http://localhost:8072/songs

resilience4j:
  circuitbreaker:
    instances:
      song-service:
        register-health-indicator: true
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

  ratelimiter:
    instances:
      song-service:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

  retry:
    instances:
      song-service:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
        ignoreExceptions:
          - com.epam.core.exception.ResourceDeletionException
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
      song-service:
        connectTimeout: 3000
        readTimeout: 8000

app:
  async:
    min-core-pool-size: 4
    max-pool-multiplier: 2
    thread-timeout: 60
    queue-capacity-multiplier: 50
    thread-name-prefix: 'song-service-async-exec-'
    keep-alive: 30
    async-request-timeout: 30000
    shutdown-wait-time: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}
    prefer-ip-address: true
